resolver: lts-13.14

packages:
- './'

extra-deps:
- github: ucsd-progsys/liquidhaskell
  commit: fe4062f339f11d4390f0b0803062f2a8f0d23dea
- github: ucsd-progsys/liquid-fixpoint
  commit: 5d2eb8fac5bc3b9a8b0cfa51afa7e5e9aa93729f
- csv-table-0.1.0.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.2
- located-base-0.1.1.1
- text-format-0.3.2
- tasty-rerun-1.1.14
- hakyll-4.12.5.2
- lrucache-1.2.0.1
